##count Nissan from CK
http://localhost:3007/api/nissansFromCK?search=Nissan

### list of cars data
http://localhost:3007/api/vehicles

### deleted vehicles
http://localhost:3007/api/vehicles/delete

